name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: List and Read file
          run: ls -ltra

        - name: Execute shell script
          run: ./ascii-script.sh

        

            #- name: List files
            #  run: ls
              
              
            #- name: Read File
            #  run: cat README.md